// <auto-generated />
using System;
using Kaits.UI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaits.UI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kaits.UI.Models.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("cod_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cod_cliente"));

                    b.Property<string>("clie_apell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clie_dociden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clie_nomb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fec_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fec_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user_creacion")
                        .HasColumnType("int");

                    b.HasKey("cod_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Kaits.UI.Models.Entities.Detalle_PedidoEntity", b =>
                {
                    b.Property<int>("Id_detped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detped"));

                    b.Property<int>("Id_Orden")
                        .HasColumnType("int");

                    b.Property<int>("cod_producto")
                        .HasColumnType("int");

                    b.Property<string>("desc_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("detped_cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("detped_precunit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("detped_subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("fec_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fec_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user_creacion")
                        .HasColumnType("int");

                    b.HasKey("Id_detped");

                    b.ToTable("Detalle_Pedido");
                });

            modelBuilder.Entity("Kaits.UI.Models.Entities.PedidoEntity", b =>
                {
                    b.Property<int>("Id_Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Orden"));

                    b.Property<int>("cod_cliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fec_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fec_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ord_fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ord_precio_total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("user_creacion")
                        .HasColumnType("int");

                    b.HasKey("Id_Orden");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Kaits.UI.Models.Entities.ProdutosEntity", b =>
                {
                    b.Property<int>("cod_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cod_producto"));

                    b.Property<DateTime?>("fec_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fec_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("prod_descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_creacion")
                        .HasColumnType("int");

                    b.HasKey("cod_producto");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
